name: Static Analysis
on:
  pull_request:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start LocalStack
        run: |
          pip install --upgrade pyopenssl
          pip install localstack awscli-local[ver1] terraform-local # install LocalStack cli and awslocal
          docker pull localstack/localstack         # Make sure to pull the latest version of the image
          localstack start -d                       # Start LocalStack in the background

          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          localstack wait -t 30                     # to become ready before timing out
          echo "Startup complete"
      - name: tflocal tests
        run: |
          tflocal init
          tflocal validate
          tflocal plan -lock=false -out terraform.plan

        # generate plain output
      - name: text
        run: tflocal show -no-color terraform.plan > terraform.text

        # generate json output
      - name: json
        run: tflocal show -json terraform.plan > terraform.json

      - name: cat files
        run: |
          cat terraform.text
          cat terraform.json

      - uses: ahmadnassri/action-terraform-report@v3
        with:
          # tell the action the plan outputs
          terraform-text: ${{ github.workspace }}/terraform.text
          terraform-json: ${{ github.workspace }}/terraform.json
          remove-stale-reports: true
